Repository arcalos-management/environment-arcalos-prod-mgmt-dev, pull requests merged in 2020-05, with the labels that each got.

#806 feat: add ingress for kuberhealthy
  env/templates/700-kuberhealthy-ing.yaml
  env/templates/kuberhealthy-basic-auth-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/M

#822 chore: remove redundant jxui backend ing and oauth
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/requirements.yaml
  env/templates/700-jxui-backend-ing.yaml
Labels: approved, lgtm, size/M

#857 feat: enable sign out functionality
  env/jxui-arcalos/values.tmpl.yaml
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#858 chore: update to new app name
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#525 chore: updated to use the latest jenkins-x-versions
  jx-requirements.yml
Labels: approved, lgtm, size/XS
