Repository arcalos-management/environment-arcalos-prod-mgmt-dev, pull requests merged in 2020-04, with the labels that each got.

#380 Revert "chore(deps): bump https://github.com/cloudbees/jxui-frontend from 0.0.1184 to 0.0.1185"
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  env/requirements.yaml
Labels: size/XS

#392 chore: increase gcactivities cleanup times
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#399 fix: remove unrecognised option
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#424 fix: specify correct values for datadog app
  env/jx-app-datadog/values.tmpl.yaml
Labels: approved, lgtm, size/S

#428 fix: attempt to remove the use if custom oauth2 image
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/S

#461 chore: corrected bot name in cluster
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#485 chore: add workspace endpoint to ing
  env/templates/700-jx-tenant-service-ing.yaml
  env/templates/701-boot-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#502 chore: init the gcp service account
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#503 chore: corrected indentation of config block
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#505 chore: removed whitespace at end of file
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, size/XS

#507 chore: revert env variable setting
  env/jxui-arcalos/values.tmpl.yaml
Labels: size/XS

#517 chore: try to init service account
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#531 chore: add a variable to display GHA name
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#575 feat: added datadog_dogrc_secret_template
  env/templates/datadog-dogrc-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#612 chore: rename arcalos-prod githubapp secret
  env/jx-tenant-service/values.tmpl.yaml
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/S

#631 chore: rox jx-tenant-service apiKey
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#650 chore: remove unused parameters
  env/parameters.tmpl.schema.json
  env/parameters.yaml
Labels: approved, lgtm, size/S

#652 chore: remove dex references
  env/values.tmpl.yaml
  systems/acme/values.tmpl.yaml
Labels: approved, lgtm, size/S

#653 chore: remove non required kube providers
  kubeProviders/aks/README.md
  kubeProviders/aks/values.tmpl.yaml
  kubeProviders/alibaba/README.md
  kubeProviders/alibaba/values.tmpl.yaml
  kubeProviders/aws/README.md
  kubeProviders/aws/values.tmpl.yaml
  kubeProviders/eks/README.md
  kubeProviders/eks/templates/irsa.tmpl.yaml
  kubeProviders/eks/templates/jenkinsx-policies.yml
  kubeProviders/eks/templates/vault_cf_tmpl.yml
  kubeProviders/eks/values.tmpl.yaml
  kubeProviders/icp/README.md
  kubeProviders/icp/values.tmpl.yaml
  kubeProviders/iks/README.md
  kubeProviders/iks/values.tmpl.yaml
  kubeProviders/minikube/values.tmpl.yaml
  kubeProviders/minishift/values.tmpl.yaml
  kubeProviders/oke/README.md
  kubeProviders/oke/values.tmpl.yaml
  kubeProviders/openshift/values.tmpl.yaml
  kubeProviders/pks/README.md
  kubeProviders/pks/values.tmpl.yaml
Labels: approved, lgtm, size/XL

#666 feat: disable use of SSO Operator in jxui-arcalos
  env/jxui-arcalos/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#667 chore: remove arcalos-secret template
  env/templates/arcalos-secret.yaml
Labels: approved, lgtm, size/S
