Repository arcalos-management/environment-arcalos-prod-mgmt-dev, pull requests merged in 2020-03, with the labels that each got.

#34 fix: correct bot name
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, size/XS

#35 chore: update jx-tenant-service and lighthouse-githubapp
  env/requirements.yaml
Labels: approved, size/XS

#36 chore: update jx-tenant-service to 0.0.450
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#37 chore: update controller config, disabled update job
  env/jx-tenant-service/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#38 chore: added arcalos-alpha-prod-secret
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/S

#50 chore(deps): bump version stream to v1.0.374
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#49 chore: disable automerging of updatebot PRs
  env/jxboot-resources/values.tmpl.yaml
Labels: size/XS

#73 fix: change arcalos producer sa secret key name
  env/jx-tenant-service/values.tmpl.yaml
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/XS

#72 fix: configuration to prevent arcalos builds
  env/templates/arcalos-scheduler.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/M

#74 chore: set new environment name value in configmap
  env/templates/arcalos-config-configmap.yaml
Labels: approved, lgtm, size/XS

#81 fix: configuration to prevent arcalos builds
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#82 chore: enabled debug for lighthouse-githubapp
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#83 fix: set jx-tenant-service url value for ligthouse-githubapp
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#84 chore: enabled debug logging on lighthotel
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#85 chore: use new private-key for lighthouse-githubapp
  env/jx-tenant-service/values.tmpl.yaml
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/S

#88 chore: enable debug logging
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#91 fix: enable extra go-scm logging
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#95 chore: revert back to original secrets for lighthouse-githubapp and tenant-service
  env/jx-tenant-service/values.tmpl.yaml
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/S

#101 chore: remove webhook logging for lighthouse-githubapp
  env/lighthouse-githubapp/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#106 chore: remove domain_issuer_url from arcalos-secret
  env/templates/arcalos-secret.yaml
Labels: approved, lgtm, size/XS

#111 chore: updateController regional location
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#107 chore: removed pipeline_user_token from arcalos-secret
  env/templates/arcalos-secret.yaml
Labels: approved, lgtm, size/XS

#108 chore: remove unused variables from arcalos-alpha-prod secret
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/XS

#126 chore: add cjxd-bot to OWNERS file
  OWNERS
Labels: size/XS

#127 chore: adding oauth2-proxy
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#129 fix: add missing args to oauth deployment
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#130 chore: test if oauth2-proxy works using the dex ingress temporarily
  env/templates/700-dex-ing.yaml
Labels: approved, lgtm, size/XS

#144 fix: add further oauth-proxy configuration
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
  env/templates/700-jxui-ing.yaml
Labels: approved, lgtm, size/S

#142 chore: pass the variable for the github app installation link
  env/jx-tenant-service/values.tmpl.yaml
Labels: size/XS

#153 chore: allow hmac api in ing
  env/templates/700-jx-tenant-service-ing.yaml
  env/templates/701-boot-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#190 fix: update oauth proxy configuration
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#191 fix: correct typo in oauth proxy values
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#193 fix: try and set approval-prompt to empty value
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#215 chore: bump version stream to 1.0.400
  env/requirements.yaml
  jx-requirements.yml
Labels: approved, lgtm, size/S

#218 fix: use custom oauth2_proxy image
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#220 feat: add an oauth-proxy for jxui-backend
  env/jxui-arcalos/values.tmpl.yaml
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/templates/700-jxui-ing.yaml
Labels: approved, lgtm, size/M

#222 fix: add oauth-proxy requirement for backend
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#224 fix: further oauth configuration changes
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
  env/templates/700-jxui-ing.yaml
Labels: approved, lgtm, size/S

#261 feat: update jxui to use new connector
  env/jxui-arcalos/values.tmpl.yaml
Labels: approved, size/XS

#299 chore: update prod app installation url
  env/jx-tenant-service/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#304 chore: refactor oauth configuration
  env/jx-app-sso/values.tmpl.yaml
  env/jxui-arcalos/values.tmpl.yaml
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
  env/requirements.yaml
  env/templates/700-dex-ing.yaml
Labels: approved, lgtm, size/M

#306 fix: remove the need to reference custom image for oauth proxy
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/S

#309 Revert "fix: remove the need to reference custom image for oauth proxy"
  env/oauth-proxy-jxui-backend/values.tmpl.yaml
  env/oauth-proxy-jxui-frontend/values.tmpl.yaml
Labels: approved, lgtm, size/S

#343 feat: use latest datadog agent and log arcalos build pods
  env/jx-app-datadog/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S
